CREATE TABLE DEMO.ROLE_USER
(
  ID NUMBER NOT NULL,
  VALUE VARCHAR2(20) NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL
);
ALTER TABLE DEMO.ROLE_USER ADD PRIMARY KEY (ID);
CREATE SEQUENCE DEMO.SEQ_ROLE_USER_GENERATOR MINVALUE 1 MAXVALUE 99999999999999 START WITH 1 INCREMENT BY 1;
