DROP USER DEMO CASCADE;
DROP USER APP_DEMO CASCADE;

create user DEMO IDENTIFIED BY i8hH7saUDa1p;
create user APP_DEMO IDENTIFIED BY CqfAWJoYu3yh;

-- GRANT CONNECT TO DEMO;
-- GRANT CONNECT, RESOURCE, DBA TO DEMO;
-- GRANT CONNECT TO APP_DEMO;
-- GRANT CONNECT, RESOURCE, DBA TO APP_DEMO;
GRANT UNLIMITED TABLESPACE TO DEMO; 
GRANT UNLIMITED TABLESPACE TO APP_DEMO; 

GRANT CONNECT TO DEMO;
GRANT CONNECT, RESOURCE, DBA TO DEMO;
GRANT CONNECT TO APP_DEMO;
GRANT CONNECT, RESOURCE, DBA TO APP_DEMO;

GRANT CREATE PROCEDURE TO DEMO;

GRANT CREATE SESSION to DEMO;
GRANT CREATE SESSION to APP_DEMO;