CREATE TABLE DEMO.EMPLEADO
(
    IDEMPLEADO NUMBER(10) NOT NULL,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    DNI VARCHAR2(12) NOT NULL,
    ESTADO_CIVIL VARCHAR2(1) NOT NULL,
    GENERO VARCHAR2(1) NOT NULL,
    EDAD NUMBER(3) NOT NULL
) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
REM INSERTING into FILEUN.TB_CATALOGO
SET DEFINE OFF;

INSERT INTO DEMO.EMPLEADO (IDEMPLEADO,NOMBRES,APELLIDOS,DNI,ESTADO_CIVIL,GENERO,EDAD) VALUES(1,'Cristhian','Paraguay','12345678','S','M',27);