CREATE TABLE DEMO.ERROR_INFO
(
  ID NUMBER NOT NULL,
  STATUS NUMBER NOT NULL,
  ERROR VARCHAR2(100) NOT NULL,
  TRACE VARCHAR2(100) NOT NULL,
  MESSAGE VARCHAR2(100) NOT NULL,
  URI_REQUESTED VARCHAR2(100) NOT NULL,
  ID_TRACKING VARCHAR2(100) NOT NULL,
  TIME_STAMP TIMESTAMP NOT NULL
);
ALTER TABLE DEMO.ERROR_INFO ADD PRIMARY KEY (ID);
CREATE SEQUENCE DEMO.SEQ_ERROR_INFO_GENERATOR MINVALUE 1 MAXVALUE 99999999999999 START WITH 1 INCREMENT BY 1;