CREATE TABLE DEMO.REFRESH_TOKEN
(
  ID NUMBER NOT NULL,
  ID_USUARIO NUMBER NOT NULL,
  VALUE VARCHAR2(100) NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL
);
ALTER TABLE DEMO.REFRESH_TOKEN ADD PRIMARY KEY (ID);
CREATE SEQUENCE DEMO.SEQ_REFRESH_TOKEN_GENERATOR MINVALUE 1 MAXVALUE 99999999999999 START WITH 1 INCREMENT BY 1;
ALTER TABLE DEMO.REFRESH_TOKEN ADD CONSTRAINT FK_DEMO_REFRESH_TOKEN_ID_USER FOREIGN KEY (ID_USUARIO) REFERENCES DEMO.USUARIO_APP(ID);
