CREATE TABLE DEMO.USUARIO_APP
(
  ID NUMBER NOT NULL,
  ACCESSKEYID VARCHAR2(20),
  SECRETACCESSKEY VARCHAR2(20),
  LOCKED NUMBER(38,2) DEFAULT 0 NOT NULL,
  ID_ROLE NUMBER NOT NULL
);
ALTER TABLE DEMO.USUARIO_APP ADD PRIMARY KEY (ID);
CREATE SEQUENCE DEMO.SEQ_USUARIO_APP_GENERATOR MINVALUE 1 MAXVALUE 99999999999999 START WITH 1 INCREMENT BY 1;
ALTER TABLE DEMO.USUARIO_APP ADD CONSTRAINT FK_DEMO_USUARIO_APP_ID_ROLE FOREIGN KEY (ID_ROLE) REFERENCES DEMO.ROLE_USER(ID);

