INSERT INTO DEMO.ROLE_USER (ID, VALUE, REGISTER_DATE) values (DEMO.SEQ_ROLE_USER_GENERATOR.NEXTVAL, 'ADMIN', sysdate);
INSERT INTO DEMO.ROLE_USER (ID, VALUE, REGISTER_DATE) values (DEMO.SEQ_ROLE_USER_GENERATOR.NEXTVAL, 'USER', sysdate);
